server:
  port: 9999
  max-http-header-size: 100000
  undertow:
    io-threads: 4


spring:
  profiles:
    active: dev
  #数据库配置
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 50
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true


topic:
  test: test

group:
  id: 1

## Mybatis配置
mybatis:
  typeAliasesPackage: com.mobstaz.financial.cloud?useUnicode=true&characterEncoding=utf8
  mapperLocations: classpath:mapper/*.xml
  type-handlers-package: com.mobstaz.financial.cloud.config.mysqlHandler
  configuration:
    map-underscore-to-camel-case: false

flyway:
  locations:classpath:/db

getui:
  serverHost: https://sms-api.yunzhenxin.com
  userCode: LdJIOdypSZFyXHZE
  authCode: 33fbbe15ad63239b90a3fd8bfd27ee91
  serviceId: qnjV4mRBPrLnMou6pUDEGz


---
spring: 
  profiles: dev 
  datasource: 
    username: pgseme-migration
    password: U7rosd1A*KXsnyddo7Uq
    url: jdbc:sqlserver://pgseme-migration.database.windows.net:1433;database=eme-migration;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

